export interface CategoryDefinition {
  id: string;
  label: string;
  icon: string;
  // Positive matching patterns (matched case-insensitively)
  keywords: (string | RegExp)[];
  // Exclusion patterns to prevent false positives (e.g., "kasvisliemi" or "vegepyörykät" in meat)
  exclude?: (string | RegExp)[];
}

export const CATEGORY_DEFINITIONS: CategoryDefinition[] = [
  {
    id: "liha",
    label: "Liha",
    icon: "meat",
    keywords: [
      /naudan/i,
      /porsaan/i,
      /sianliha/i,
      /härän/i,
      /härkä/i,
      /lihapull/i,
      /jauheliha/i,
      /possu/i,
      /pekoni/i,
      /kylkipaisti/i,
      /kinkku/i,
      /makkara/i,
      /nakki/i,
      /karjalanpaist/i,
      /lihamureke/i,
      /lammas/i,
      /lampaan/i,
      /karitsan?/i,
      /paahtopaist/i,
      /hirven/i,
      /poron/i,
      /peuran/i,
      /riista/i,
      /\bpork\b/i,
      /\bbeef\b/i,
      /\bsteak\b/i,
      /\bbacon\b/i,
      /\bliha\b/i,
      /\blihaa\b/i,
      /liharuoka/i,
      /lihapata/i,
      /lihakeitto/i,
      /lehtipihvi/i,
    ],
    exclude: [
      /kasvis/i,
      /vege/i,
      /vegaani/i,
      /soija/i,
      /tofu/i,
      /härkis/i,
      /mif[uù]/i,
      /seitan/i,
    ],
  },
  {
    id: "kala",
    label: "Kala",
    icon: "fish",
    keywords: [
      /lohi/i,
      /lohta/i,
      /kirjoloh/i,
      /\bsei\b/i,
      /seiti/i,
      /turska/i,
      /kuha/i,
      /siika/i,
      /ahven/i,
      /silakka/i,
      /muikku/i,
      /kalapuiko/i,
      /kalaleik/i,
      /kalamureke/i,
      /kalapihv/i,
      /rapu/i,
      /katkarap/i,
      /simpukk/i,
      /\bseafood\b/i,
      /\bfish\b/i,
      /\bsalmon\b/i,
      /\btuna\b/i,
      /tonnikal/i,
      /\bkala\b/i,
      /\bkalaa\b/i,
      /kalaruoka/i,
      /kalakeitto/i,
      /kalapata/i,
      /kalavuoka/i,
    ],
    exclude: [/kasvis/i, /vege/i, /vegaani/i, /soija/i, /tofu/i, /härkis/i],
  },
  {
    id: "kana",
    label: "Kana",
    icon: "chicken",
    keywords: [
      /kana/i,
      /broileri/i,
      /kalkkuna/i,
      /wings/i,
      /\bchicken\b/i,
      /\bpoultry\b/i,
      /\bturkey\b/i,
      /kanapihv/i,
      /kanan/i,
      /kanapull/i,
      /kanaleik/i,
      /kanakoipi/i,
      /kanasiip/i,
      /kananpoika/i,
      /kanakastik/i,
      /kanakeitto/i,
      /kanapata/i,
      /broiler/i,
    ],
    exclude: [/kasvis/i, /vege/i, /vegaani/i, /soija/i, /tofu/i, /härkis/i],
  },
  {
    id: "vege",
    label: "Vege",
    icon: "vegan",
    keywords: [
      /vegaani/i,
      /\bvege\b/i,
      /vege-/i,
      /vege/i,
      /\bvegan\b/i,
      /plant-based/i,
      /tofu/i,
      /soija/i,
      /härkis/i,
      /seitan/i,
      /kaurapohj/i,
      /mif[uù]/i,
      /falafel/i,
      /herneproteiin/i,
      /linssi/i,
      /papu/i,
      /pavut/i,
      /chickpea/i,
      /kikherne/i,
    ],
  },
  {
    id: "kasvis",
    label: "Kasvis",
    icon: "vege",
    keywords: [
      /kasvis/i,
      /vegetar/i,
      /vege/i,
      /vegaani/i,
      /kasvisruoka/i,
      /kasvispihv/i,
      /kasvispull/i,
      /kasviskeitto/i,
      /kasvislasagne/i,
      /kasviscurry/i,
      /kasviswok/i,
      /juusto/i,
      /halloum/i,
      /feta/i,
      /mozzarella/i,
      /tofu/i,
      /soija/i,
      /härkis/i,
      /seitan/i,
      /mif[uù]/i,
      /falafel/i,
      /pinaatti/i,
      /porkkana/i,
      /kukkakaal/i,
      /parsakaal/i,
      /bataatti/i,
      /munakoiso/i,
      /kesäkurpitsa/i,
    ],
    exclude: [
      /naudan/i,
      /porsaan/i,
      /\bliha\b/i,
      /\bkana\b/i,
      /broileri/i,
      /lohi/i,
      /\bkala\b/i,
      /pekoni/i,
    ],
  },
  {
    id: "burgeri",
    label: "Burgeri",
    icon: "burger",
    keywords: [/burger/i, /hampurilai/i, /slider/i, /cheeseburger/i],
  },
  {
    id: "pizza",
    label: "Pizza",
    icon: "pizza",
    keywords: [/pizza/i, /pitsa/i, /pizzat/i, /pizzapohja/i],
  },
  {
    id: "aasialainen",
    label: "Aasialainen",
    icon: "asian",
    keywords: [
      /curry/i,
      /wok/i,
      /wokki/i,
      /ramen/i,
      /teriyaki/i,
      /tikka/i,
      /korma/i,
      /pad thai/i,
      /sushi/i,
      /tom yum/i,
      /tom kha/i,
      /\bbao\b/i,
      /masala/i,
      /butter chicken/i,
      /dahl/i,
      /kimchi/i,
      /dumpling/i,
      /gyoza/i,
      /vietnam/i,
      /thai/i,
      /intialai/i,
      /kiinalai/i,
      /japanilai/i,
      /\bpho\b/i,
      /noodeli/i,
      /nuudeli/i,
      /noodles/i,
      /yakitori/i,
      /katsu/i,
      /tandoori/i,
      /samosa/i,
    ],
  },
  {
    id: "tex-mex",
    label: "Tex Mex",
    icon: "texmex",
    keywords: [
      /taco/i,
      /burrito/i,
      /quesadilla/i,
      /fajita/i,
      /nacho/i,
      /enchilada/i,
      /chili con carne/i,
      /chili sin carne/i,
      /salsa/i,
      /guacamole/i,
      /tortilla/i,
      /tex-mex/i,
      /tex mex/i,
      /meksikol/i,
      /mexican/i,
    ],
  },
];
