name: Cron job to update root page

on:
  schedule:
    # GitHub runs cron jobs on UTC +0 time. We want this job to run everyday
    # at 8 o'clock. Finland's timezone is +3 in summer and +2 on winter.
    # So this job runs at 8 o'clock in summer and at 7 o'click in winter.
    # * is a special character in YAML so you have to quote this string
    - cron: '0 5 * * *'

jobs:
  revalidate_root:
    name: Revalidate root page
    runs-on: ubuntu-latest
    steps:
      - name: Call next app's revalidate url 📡
        uses: satak/webrequest-action@master
        with:
          url: https://yle-campus-lunch-list.vercel.app/api/revalidate/current-day-menus?secret=${{ secrets.NEXT_APP_REVALIDATION_TOKEN }}
          method: GET
          timeout: 15000
